variables:
  MVN_IMAGE: "maven:3.8-openjdk-17"
  MVN_PROJECT_ROOT: ${CI_PROJECT_DIR}
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - validate
  - scan
  - build
  - package
  - deploy
  - test
  - cleanup
  
.base::java-base:
  image: 
    name: "$MVN_IMAGE"
  tags:
    - java
  before_script:
    - cd ${MVN_PROJECT_ROOT}
    - mvn --version

.validate::java-validate:
  extends: .base::java-base
  stage: validate
  script:
    - mvn validate

.scan::java-scan:
  extends: .base::java-base
  stage: scan
  script:
    - echo "Scanning java project..."

.build::java-compile:
  extends: .base::java-base
  stage: build
  script:
    - echo "Building java project..."
    - mvn compile

.build::java-unit-test:
  extends: .base::java-base
  stage: build
  script:
    - echo "Running java tests..."
    - mvn test

.package::java-package:
  extends: .base::java-base
  stage: package
  script:
    - echo "Building java package..."
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - ${MVN_PROJECT_ROOT}/target/*.jar
    access: 'developer'
    expire_in: "5 days"

.package::java-oci-build:
  extends: .base::java-base
  stage: package
  needs:
    - .package::java-package
  script:
    - echo "Building docker image for java app..."
    # - docker build . -t java-test-jar:latest
    - echo "Pushing docker image for java app..."
    # - docker push java-test-jar:latest

.deploy::java-oci-deploy:
  extends: .base::java-base
  stage: deploy
  script:
    - echo "Deploy java oci to k8s..."
    # - kubectl apply -f ci-test-jar.yaml...

.test::java-security-test:
  extends: .base::java-base
  stage: test
  script:
    - echo "OWASP ZAP testing deployed java app..."

.cleanup::java-cleanup:
  extends: .base::java-base
  stage: cleanup
  script:
    - echo "Cleanup java..."
    - mvn clean
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DESTROY_INFRA == "true"   # Requires explicit var value
      when: manual
